# SPDX-License-Identifier: Apache-2.0

FROM quay.io/projectquay/golang:1.22 AS makefile

RUN dnf install -qy diffutils && dnf clean all

WORKDIR /kubesan

# Although "make" will also do "go mod download", doing it as a separate
# RUN now lets us cache things for faster container reuse
COPY go.mod go.sum Makefile ./
RUN go mod download

# Although "make" will also build these tools, pre-building them as a
# separate RUN now lets us cache things for faster container reuse
RUN make controller-gen golangci-lint

# Copy only source files, not generated binaries, since binaries built
# in the host environment may not work in the container environment.
# If .generate.timestamp exists in the host, we assume that the files
# generated by controller-gen are already up-to-date and don't need to
# be rebuilt; use of the ? allows the glob to pass if the file does not
# exist, such as in a CI environment on a fresh checkout.
COPY PROJECT .generate?timestamp ./
COPY api/ api/
COPY cmd/ cmd/
COPY deploy/ deploy/
COPY hack/ hack/
COPY internal/ internal/

RUN make build

# CentOS Stream 9 doesn't provide package nbd
# FROM quay.io/centos/centos:stream9
FROM quay.io/fedora/fedora:40

# util-linux-core, e2fsprogs, and xfsprogs are for Filesystem volume support where
# blkid(8) and mkfs are required by k8s.io/mount-utils.
RUN dnf install -qy nbd qemu-img util-linux-core e2fsprogs xfsprogs && dnf clean all

WORKDIR /kubesan

COPY --from=makefile /kubesan/bin/kubesan bin/

ENTRYPOINT [ "/kubesan/bin/kubesan" ]
