# SPDX-License-Identifier: Apache-2.0
ARG TARGETOS
ARG TARGETARCH
ARG TARGETPLATFORM
FROM golang:1.22 AS builder

WORKDIR /kubesan

COPY go.mod go.sum Makefile ./
COPY vendor vendor/
RUN go mod verify

# Copy only source files, not generated binaries, since binaries built
# in the host environment may not work in the container environment.
# If .generate.timestamp exists in the host, we assume that the files
# generated by controller-gen are already up-to-date and don't need to
# be rebuilt; use of the ? allows the glob to pass if the file does not
# exist, such as in a CI environment on a fresh checkout.
COPY PROJECT .generate?timestamp ./
COPY api/ api/
COPY cmd/ cmd/
COPY deploy/ deploy/
COPY hack/ hack/
COPY internal/ internal/

RUN GOOS=$TARGETOS GOARCH=$TARGETARCH go build -mod=vendor --ldflags "-s -w" -a -o bin/kubesan cmd/main.go

# CentOS Stream 9 doesn't provide package nbd
# FROM quay.io/centos/centos:stream9
FROM --platform=$TARGETPLATFORM fedora:latest

# util-linux-core, e2fsprogs, and xfsprogs are for Filesystem volume support where
# blkid(8) and mkfs are required by k8s.io/mount-utils.
RUN dnf update -y && dnf install --nodocs --noplugins -qy nbd qemu-img util-linux-core e2fsprogs xfsprogs && dnf clean all

WORKDIR /

COPY --from=builder /kubesan/bin/kubesan .

ENTRYPOINT [ "/kubesan" ]
