//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlobPool) DeepCopyInto(out *BlobPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlobPool.
func (in *BlobPool) DeepCopy() *BlobPool {
	if in == nil {
		return nil
	}
	out := new(BlobPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BlobPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlobPoolHolder) DeepCopyInto(out *BlobPoolHolder) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlobPoolHolder.
func (in *BlobPoolHolder) DeepCopy() *BlobPoolHolder {
	if in == nil {
		return nil
	}
	out := new(BlobPoolHolder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlobPoolList) DeepCopyInto(out *BlobPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BlobPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlobPoolList.
func (in *BlobPoolList) DeepCopy() *BlobPoolList {
	if in == nil {
		return nil
	}
	out := new(BlobPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BlobPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlobPoolSpec) DeepCopyInto(out *BlobPoolSpec) {
	*out = *in
	if in.Blobs != nil {
		in, out := &in.Blobs, &out.Blobs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ActiveOnNode != nil {
		in, out := &in.ActiveOnNode, &out.ActiveOnNode
		*out = new(string)
		**out = **in
	}
	if in.Holders != nil {
		in, out := &in.Holders, &out.Holders
		*out = make([]BlobPoolHolder, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlobPoolSpec.
func (in *BlobPoolSpec) DeepCopy() *BlobPoolSpec {
	if in == nil {
		return nil
	}
	out := new(BlobPoolSpec)
	in.DeepCopyInto(out)
	return out
}
