//go:build !ignore_autogenerated

// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceSwitch) DeepCopyInto(out *DeviceSwitch) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceSwitch.
func (in *DeviceSwitch) DeepCopy() *DeviceSwitch {
	if in == nil {
		return nil
	}
	out := new(DeviceSwitch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeviceSwitch) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceSwitchList) DeepCopyInto(out *DeviceSwitchList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DeviceSwitch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceSwitchList.
func (in *DeviceSwitchList) DeepCopy() *DeviceSwitchList {
	if in == nil {
		return nil
	}
	out := new(DeviceSwitchList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeviceSwitchList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceSwitchSpec) DeepCopyInto(out *DeviceSwitchSpec) {
	*out = *in
	if in.InputURI != nil {
		in, out := &in.InputURI, &out.InputURI
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceSwitchSpec.
func (in *DeviceSwitchSpec) DeepCopy() *DeviceSwitchSpec {
	if in == nil {
		return nil
	}
	out := new(DeviceSwitchSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceSwitchStatus) DeepCopyInto(out *DeviceSwitchStatus) {
	*out = *in
	if in.Node != nil {
		in, out := &in.Node, &out.Node
		*out = new(string)
		**out = **in
	}
	if in.OutputPath != nil {
		in, out := &in.OutputPath, &out.OutputPath
		*out = new(string)
		**out = **in
	}
	if in.SizeBytes != nil {
		in, out := &in.SizeBytes, &out.SizeBytes
		*out = new(int64)
		**out = **in
	}
	if in.InputURI != nil {
		in, out := &in.InputURI, &out.InputURI
		*out = new(string)
		**out = **in
	}
	if in.NbdDevice != nil {
		in, out := &in.NbdDevice, &out.NbdDevice
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceSwitchStatus.
func (in *DeviceSwitchStatus) DeepCopy() *DeviceSwitchStatus {
	if in == nil {
		return nil
	}
	out := new(DeviceSwitchStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbdServer) DeepCopyInto(out *NbdServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbdServer.
func (in *NbdServer) DeepCopy() *NbdServer {
	if in == nil {
		return nil
	}
	out := new(NbdServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NbdServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbdServerList) DeepCopyInto(out *NbdServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NbdServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbdServerList.
func (in *NbdServerList) DeepCopy() *NbdServerList {
	if in == nil {
		return nil
	}
	out := new(NbdServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NbdServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbdServerSpec) DeepCopyInto(out *NbdServerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbdServerSpec.
func (in *NbdServerSpec) DeepCopy() *NbdServerSpec {
	if in == nil {
		return nil
	}
	out := new(NbdServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbdServerStatus) DeepCopyInto(out *NbdServerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbdServerStatus.
func (in *NbdServerStatus) DeepCopy() *NbdServerStatus {
	if in == nil {
		return nil
	}
	out := new(NbdServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Snapshot) DeepCopyInto(out *Snapshot) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Snapshot.
func (in *Snapshot) DeepCopy() *Snapshot {
	if in == nil {
		return nil
	}
	out := new(Snapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Snapshot) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotList) DeepCopyInto(out *SnapshotList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Snapshot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotList.
func (in *SnapshotList) DeepCopy() *SnapshotList {
	if in == nil {
		return nil
	}
	out := new(SnapshotList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SnapshotList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotSpec) DeepCopyInto(out *SnapshotSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotSpec.
func (in *SnapshotSpec) DeepCopy() *SnapshotSpec {
	if in == nil {
		return nil
	}
	out := new(SnapshotSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotStatus) DeepCopyInto(out *SnapshotStatus) {
	*out = *in
	if in.CreationTime != nil {
		in, out := &in.CreationTime, &out.CreationTime
		*out = (*in).DeepCopy()
	}
	if in.SizeBytes != nil {
		in, out := &in.SizeBytes, &out.SizeBytes
		*out = new(int64)
		**out = **in
	}
	if in.FsType != nil {
		in, out := &in.FsType, &out.FsType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotStatus.
func (in *SnapshotStatus) DeepCopy() *SnapshotStatus {
	if in == nil {
		return nil
	}
	out := new(SnapshotStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThinBlob) DeepCopyInto(out *ThinBlob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThinBlob.
func (in *ThinBlob) DeepCopy() *ThinBlob {
	if in == nil {
		return nil
	}
	out := new(ThinBlob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ThinBlob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThinBlobAttachment) DeepCopyInto(out *ThinBlobAttachment) {
	*out = *in
	in.State.DeepCopyInto(&out.State)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThinBlobAttachment.
func (in *ThinBlobAttachment) DeepCopy() *ThinBlobAttachment {
	if in == nil {
		return nil
	}
	out := new(ThinBlobAttachment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThinBlobAttachmentState) DeepCopyInto(out *ThinBlobAttachmentState) {
	*out = *in
	if in.Attaching != nil {
		in, out := &in.Attaching, &out.Attaching
		*out = new(ThinBlobAttachmentStateAttaching)
		**out = **in
	}
	if in.AttachedLocal != nil {
		in, out := &in.AttachedLocal, &out.AttachedLocal
		*out = new(ThinBlobAttachmentStateAttachedLocal)
		**out = **in
	}
	if in.AttachedRemote != nil {
		in, out := &in.AttachedRemote, &out.AttachedRemote
		*out = new(ThinBlobAttachmentStateAttachedRemote)
		**out = **in
	}
	if in.Detaching != nil {
		in, out := &in.Detaching, &out.Detaching
		*out = new(ThinBlobAttachmentStateDetaching)
		**out = **in
	}
	if in.Suspending != nil {
		in, out := &in.Suspending, &out.Suspending
		*out = new(ThinBlobAttachmentStateSuspending)
		**out = **in
	}
	if in.Suspended != nil {
		in, out := &in.Suspended, &out.Suspended
		*out = new(ThinBlobAttachmentStateSuspended)
		**out = **in
	}
	if in.Resuming != nil {
		in, out := &in.Resuming, &out.Resuming
		*out = new(ThinBlobAttachmentStateResuming)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThinBlobAttachmentState.
func (in *ThinBlobAttachmentState) DeepCopy() *ThinBlobAttachmentState {
	if in == nil {
		return nil
	}
	out := new(ThinBlobAttachmentState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThinBlobAttachmentStateAttachedLocal) DeepCopyInto(out *ThinBlobAttachmentStateAttachedLocal) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThinBlobAttachmentStateAttachedLocal.
func (in *ThinBlobAttachmentStateAttachedLocal) DeepCopy() *ThinBlobAttachmentStateAttachedLocal {
	if in == nil {
		return nil
	}
	out := new(ThinBlobAttachmentStateAttachedLocal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThinBlobAttachmentStateAttachedRemote) DeepCopyInto(out *ThinBlobAttachmentStateAttachedRemote) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThinBlobAttachmentStateAttachedRemote.
func (in *ThinBlobAttachmentStateAttachedRemote) DeepCopy() *ThinBlobAttachmentStateAttachedRemote {
	if in == nil {
		return nil
	}
	out := new(ThinBlobAttachmentStateAttachedRemote)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThinBlobAttachmentStateAttaching) DeepCopyInto(out *ThinBlobAttachmentStateAttaching) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThinBlobAttachmentStateAttaching.
func (in *ThinBlobAttachmentStateAttaching) DeepCopy() *ThinBlobAttachmentStateAttaching {
	if in == nil {
		return nil
	}
	out := new(ThinBlobAttachmentStateAttaching)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThinBlobAttachmentStateDetaching) DeepCopyInto(out *ThinBlobAttachmentStateDetaching) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThinBlobAttachmentStateDetaching.
func (in *ThinBlobAttachmentStateDetaching) DeepCopy() *ThinBlobAttachmentStateDetaching {
	if in == nil {
		return nil
	}
	out := new(ThinBlobAttachmentStateDetaching)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThinBlobAttachmentStateResuming) DeepCopyInto(out *ThinBlobAttachmentStateResuming) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThinBlobAttachmentStateResuming.
func (in *ThinBlobAttachmentStateResuming) DeepCopy() *ThinBlobAttachmentStateResuming {
	if in == nil {
		return nil
	}
	out := new(ThinBlobAttachmentStateResuming)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThinBlobAttachmentStateSuspended) DeepCopyInto(out *ThinBlobAttachmentStateSuspended) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThinBlobAttachmentStateSuspended.
func (in *ThinBlobAttachmentStateSuspended) DeepCopy() *ThinBlobAttachmentStateSuspended {
	if in == nil {
		return nil
	}
	out := new(ThinBlobAttachmentStateSuspended)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThinBlobAttachmentStateSuspending) DeepCopyInto(out *ThinBlobAttachmentStateSuspending) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThinBlobAttachmentStateSuspending.
func (in *ThinBlobAttachmentStateSuspending) DeepCopy() *ThinBlobAttachmentStateSuspending {
	if in == nil {
		return nil
	}
	out := new(ThinBlobAttachmentStateSuspending)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThinBlobContents) DeepCopyInto(out *ThinBlobContents) {
	*out = *in
	if in.Empty != nil {
		in, out := &in.Empty, &out.Empty
		*out = new(ThinBlobContentsEmpty)
		**out = **in
	}
	if in.Filesystem != nil {
		in, out := &in.Filesystem, &out.Filesystem
		*out = new(ThinBlobContentsFilesystem)
		**out = **in
	}
	if in.Copy != nil {
		in, out := &in.Copy, &out.Copy
		*out = new(ThinBlobContentsCopy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThinBlobContents.
func (in *ThinBlobContents) DeepCopy() *ThinBlobContents {
	if in == nil {
		return nil
	}
	out := new(ThinBlobContents)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThinBlobContentsCopy) DeepCopyInto(out *ThinBlobContentsCopy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThinBlobContentsCopy.
func (in *ThinBlobContentsCopy) DeepCopy() *ThinBlobContentsCopy {
	if in == nil {
		return nil
	}
	out := new(ThinBlobContentsCopy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThinBlobContentsEmpty) DeepCopyInto(out *ThinBlobContentsEmpty) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThinBlobContentsEmpty.
func (in *ThinBlobContentsEmpty) DeepCopy() *ThinBlobContentsEmpty {
	if in == nil {
		return nil
	}
	out := new(ThinBlobContentsEmpty)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThinBlobContentsFilesystem) DeepCopyInto(out *ThinBlobContentsFilesystem) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThinBlobContentsFilesystem.
func (in *ThinBlobContentsFilesystem) DeepCopy() *ThinBlobContentsFilesystem {
	if in == nil {
		return nil
	}
	out := new(ThinBlobContentsFilesystem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThinBlobList) DeepCopyInto(out *ThinBlobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ThinBlob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThinBlobList.
func (in *ThinBlobList) DeepCopy() *ThinBlobList {
	if in == nil {
		return nil
	}
	out := new(ThinBlobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ThinBlobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThinBlobSpec) DeepCopyInto(out *ThinBlobSpec) {
	*out = *in
	in.Contents.DeepCopyInto(&out.Contents)
	if in.AttachToNodes != nil {
		in, out := &in.AttachToNodes, &out.AttachToNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThinBlobSpec.
func (in *ThinBlobSpec) DeepCopy() *ThinBlobSpec {
	if in == nil {
		return nil
	}
	out := new(ThinBlobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThinBlobState) DeepCopyInto(out *ThinBlobState) {
	*out = *in
	if in.Creating != nil {
		in, out := &in.Creating, &out.Creating
		*out = new(ThinBlobStateCreating)
		**out = **in
	}
	if in.Ready != nil {
		in, out := &in.Ready, &out.Ready
		*out = new(ThinBlobStateReady)
		**out = **in
	}
	if in.Expanding != nil {
		in, out := &in.Expanding, &out.Expanding
		*out = new(ThinBlobStateExpanding)
		**out = **in
	}
	if in.Migrating != nil {
		in, out := &in.Migrating, &out.Migrating
		*out = new(ThinBlobStateMigrating)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThinBlobState.
func (in *ThinBlobState) DeepCopy() *ThinBlobState {
	if in == nil {
		return nil
	}
	out := new(ThinBlobState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThinBlobStateCreating) DeepCopyInto(out *ThinBlobStateCreating) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThinBlobStateCreating.
func (in *ThinBlobStateCreating) DeepCopy() *ThinBlobStateCreating {
	if in == nil {
		return nil
	}
	out := new(ThinBlobStateCreating)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThinBlobStateExpanding) DeepCopyInto(out *ThinBlobStateExpanding) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThinBlobStateExpanding.
func (in *ThinBlobStateExpanding) DeepCopy() *ThinBlobStateExpanding {
	if in == nil {
		return nil
	}
	out := new(ThinBlobStateExpanding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThinBlobStateMigrating) DeepCopyInto(out *ThinBlobStateMigrating) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThinBlobStateMigrating.
func (in *ThinBlobStateMigrating) DeepCopy() *ThinBlobStateMigrating {
	if in == nil {
		return nil
	}
	out := new(ThinBlobStateMigrating)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThinBlobStateReady) DeepCopyInto(out *ThinBlobStateReady) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThinBlobStateReady.
func (in *ThinBlobStateReady) DeepCopy() *ThinBlobStateReady {
	if in == nil {
		return nil
	}
	out := new(ThinBlobStateReady)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThinBlobStatus) DeepCopyInto(out *ThinBlobStatus) {
	*out = *in
	in.State.DeepCopyInto(&out.State)
	if in.ThinPoolLvName != nil {
		in, out := &in.ThinPoolLvName, &out.ThinPoolLvName
		*out = new(string)
		**out = **in
	}
	if in.FsType != nil {
		in, out := &in.FsType, &out.FsType
		*out = new(string)
		**out = **in
	}
	if in.Attachments != nil {
		in, out := &in.Attachments, &out.Attachments
		*out = make([]ThinBlobAttachment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThinBlobStatus.
func (in *ThinBlobStatus) DeepCopy() *ThinBlobStatus {
	if in == nil {
		return nil
	}
	out := new(ThinBlobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThinLv) DeepCopyInto(out *ThinLv) {
	*out = *in
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(ThinLvSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(ThinLvStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThinLv.
func (in *ThinLv) DeepCopy() *ThinLv {
	if in == nil {
		return nil
	}
	out := new(ThinLv)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThinLvContents) DeepCopyInto(out *ThinLvContents) {
	*out = *in
	if in.Empty != nil {
		in, out := &in.Empty, &out.Empty
		*out = new(ThinLvContentsEmpty)
		**out = **in
	}
	if in.Snapshot != nil {
		in, out := &in.Snapshot, &out.Snapshot
		*out = new(ThinLvContentsSnapshot)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThinLvContents.
func (in *ThinLvContents) DeepCopy() *ThinLvContents {
	if in == nil {
		return nil
	}
	out := new(ThinLvContents)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThinLvContentsEmpty) DeepCopyInto(out *ThinLvContentsEmpty) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThinLvContentsEmpty.
func (in *ThinLvContentsEmpty) DeepCopy() *ThinLvContentsEmpty {
	if in == nil {
		return nil
	}
	out := new(ThinLvContentsEmpty)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThinLvContentsSnapshot) DeepCopyInto(out *ThinLvContentsSnapshot) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThinLvContentsSnapshot.
func (in *ThinLvContentsSnapshot) DeepCopy() *ThinLvContentsSnapshot {
	if in == nil {
		return nil
	}
	out := new(ThinLvContentsSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThinLvSpec) DeepCopyInto(out *ThinLvSpec) {
	*out = *in
	in.Contents.DeepCopyInto(&out.Contents)
	if in.PreferredNode != nil {
		in, out := &in.PreferredNode, &out.PreferredNode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThinLvSpec.
func (in *ThinLvSpec) DeepCopy() *ThinLvSpec {
	if in == nil {
		return nil
	}
	out := new(ThinLvSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThinLvState) DeepCopyInto(out *ThinLvState) {
	*out = *in
	if in.Inactive != nil {
		in, out := &in.Inactive, &out.Inactive
		*out = new(ThinLvStateInactive)
		**out = **in
	}
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(ThinLvStateActive)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThinLvState.
func (in *ThinLvState) DeepCopy() *ThinLvState {
	if in == nil {
		return nil
	}
	out := new(ThinLvState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThinLvStateActive) DeepCopyInto(out *ThinLvStateActive) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThinLvStateActive.
func (in *ThinLvStateActive) DeepCopy() *ThinLvStateActive {
	if in == nil {
		return nil
	}
	out := new(ThinLvStateActive)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThinLvStateCreating) DeepCopyInto(out *ThinLvStateCreating) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThinLvStateCreating.
func (in *ThinLvStateCreating) DeepCopy() *ThinLvStateCreating {
	if in == nil {
		return nil
	}
	out := new(ThinLvStateCreating)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThinLvStateInactive) DeepCopyInto(out *ThinLvStateInactive) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThinLvStateInactive.
func (in *ThinLvStateInactive) DeepCopy() *ThinLvStateInactive {
	if in == nil {
		return nil
	}
	out := new(ThinLvStateInactive)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThinLvStatus) DeepCopyInto(out *ThinLvStatus) {
	*out = *in
	in.State.DeepCopyInto(&out.State)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThinLvStatus.
func (in *ThinLvStatus) DeepCopy() *ThinLvStatus {
	if in == nil {
		return nil
	}
	out := new(ThinLvStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThinPoolLv) DeepCopyInto(out *ThinPoolLv) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThinPoolLv.
func (in *ThinPoolLv) DeepCopy() *ThinPoolLv {
	if in == nil {
		return nil
	}
	out := new(ThinPoolLv)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ThinPoolLv) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThinPoolLvList) DeepCopyInto(out *ThinPoolLvList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ThinPoolLv, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThinPoolLvList.
func (in *ThinPoolLvList) DeepCopy() *ThinPoolLvList {
	if in == nil {
		return nil
	}
	out := new(ThinPoolLvList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ThinPoolLvList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThinPoolLvSpec) DeepCopyInto(out *ThinPoolLvSpec) {
	*out = *in
	if in.ThinLvs != nil {
		in, out := &in.ThinLvs, &out.ThinLvs
		*out = make([]ThinLvSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThinPoolLvSpec.
func (in *ThinPoolLvSpec) DeepCopy() *ThinPoolLvSpec {
	if in == nil {
		return nil
	}
	out := new(ThinPoolLvSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThinPoolLvStatus) DeepCopyInto(out *ThinPoolLvStatus) {
	*out = *in
	if in.ActiveOnNode != nil {
		in, out := &in.ActiveOnNode, &out.ActiveOnNode
		*out = new(string)
		**out = **in
	}
	if in.ThinLvs != nil {
		in, out := &in.ThinLvs, &out.ThinLvs
		*out = make([]ThinLvStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThinPoolLvStatus.
func (in *ThinPoolLvStatus) DeepCopy() *ThinPoolLvStatus {
	if in == nil {
		return nil
	}
	out := new(ThinPoolLvStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Volume) DeepCopyInto(out *Volume) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Volume.
func (in *Volume) DeepCopy() *Volume {
	if in == nil {
		return nil
	}
	out := new(Volume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Volume) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeContents) DeepCopyInto(out *VolumeContents) {
	*out = *in
	if in.Empty != nil {
		in, out := &in.Empty, &out.Empty
		*out = new(VolumeContentsEmpty)
		**out = **in
	}
	if in.CloneVolume != nil {
		in, out := &in.CloneVolume, &out.CloneVolume
		*out = new(VolumeContentsCloneVolume)
		**out = **in
	}
	if in.CloneSnapshot != nil {
		in, out := &in.CloneSnapshot, &out.CloneSnapshot
		*out = new(VolumeContentsCloneSnapshot)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeContents.
func (in *VolumeContents) DeepCopy() *VolumeContents {
	if in == nil {
		return nil
	}
	out := new(VolumeContents)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeContentsCloneSnapshot) DeepCopyInto(out *VolumeContentsCloneSnapshot) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeContentsCloneSnapshot.
func (in *VolumeContentsCloneSnapshot) DeepCopy() *VolumeContentsCloneSnapshot {
	if in == nil {
		return nil
	}
	out := new(VolumeContentsCloneSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeContentsCloneVolume) DeepCopyInto(out *VolumeContentsCloneVolume) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeContentsCloneVolume.
func (in *VolumeContentsCloneVolume) DeepCopy() *VolumeContentsCloneVolume {
	if in == nil {
		return nil
	}
	out := new(VolumeContentsCloneVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeContentsEmpty) DeepCopyInto(out *VolumeContentsEmpty) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeContentsEmpty.
func (in *VolumeContentsEmpty) DeepCopy() *VolumeContentsEmpty {
	if in == nil {
		return nil
	}
	out := new(VolumeContentsEmpty)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeList) DeepCopyInto(out *VolumeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Volume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeList.
func (in *VolumeList) DeepCopy() *VolumeList {
	if in == nil {
		return nil
	}
	out := new(VolumeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VolumeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeSpec) DeepCopyInto(out *VolumeSpec) {
	*out = *in
	in.Type.DeepCopyInto(&out.Type)
	in.Contents.DeepCopyInto(&out.Contents)
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]VolumeAccessMode, len(*in))
		copy(*out, *in)
	}
	if in.AttachToNodes != nil {
		in, out := &in.AttachToNodes, &out.AttachToNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeSpec.
func (in *VolumeSpec) DeepCopy() *VolumeSpec {
	if in == nil {
		return nil
	}
	out := new(VolumeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeStatus) DeepCopyInto(out *VolumeStatus) {
	*out = *in
	if in.FsType != nil {
		in, out := &in.FsType, &out.FsType
		*out = new(string)
		**out = **in
	}
	if in.AttachedToNodes != nil {
		in, out := &in.AttachedToNodes, &out.AttachedToNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeStatus.
func (in *VolumeStatus) DeepCopy() *VolumeStatus {
	if in == nil {
		return nil
	}
	out := new(VolumeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeType) DeepCopyInto(out *VolumeType) {
	*out = *in
	if in.Block != nil {
		in, out := &in.Block, &out.Block
		*out = new(VolumeTypeBlock)
		**out = **in
	}
	if in.Filesystem != nil {
		in, out := &in.Filesystem, &out.Filesystem
		*out = new(VolumeTypeFilesystem)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeType.
func (in *VolumeType) DeepCopy() *VolumeType {
	if in == nil {
		return nil
	}
	out := new(VolumeType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeTypeBlock) DeepCopyInto(out *VolumeTypeBlock) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeTypeBlock.
func (in *VolumeTypeBlock) DeepCopy() *VolumeTypeBlock {
	if in == nil {
		return nil
	}
	out := new(VolumeTypeBlock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeTypeFilesystem) DeepCopyInto(out *VolumeTypeFilesystem) {
	*out = *in
	if in.MountOptions != nil {
		in, out := &in.MountOptions, &out.MountOptions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeTypeFilesystem.
func (in *VolumeTypeFilesystem) DeepCopy() *VolumeTypeFilesystem {
	if in == nil {
		return nil
	}
	out := new(VolumeTypeFilesystem)
	in.DeepCopyInto(out)
	return out
}
